### ISSUE TITLE
Bosh.io throws 500 error on bosh upload release.

### ISSUE THREAD

**Issue by haydonryan** [starkandwayne/bosh-errand-resource-boshrelease#2]
Hey Guys,
 Looks like this isn't listed in the bosh.io site. Running the command:

`bosh upload release https://bosh.io/d/github.com/cloudfoundry-community/bosh-errand-resource-boshrelease`

Throws a 500 error from bosh.io.

I also posted on the #bosh  Slack channel.

Take care,
 Haydon

**Comment by drnic** [comment]
@cppforlife can this repo be added to bosh.io please?

Nic

**Comment by cppforlife** [comment]
@drnic Added. Arguably though this should be a reusable task image instead of a resource...

**Comment by drnic** [comment]
Resource images are great. It's still pretty efficient to load them in via bosh like Concourse loads in its own built-in reaource types.

On Mon, May 30, 2016 at 4:19 PM -0700, "Dmitriy Kalinin" notifications@github.com wrote:

@drnic Added. Arguably though this should be a reusable task image instead of a resource...

**Comment by haydonryan** [comment]
Followup:
concourse 1.2 doesn't have the Image locations for resources in the manifest.... I'm guessing that this is still how it's added in the manifest
